spring.config.import=optional:file:.env[.properties]

spring.application.name=speed-dating
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#MVP ONLY
spring.jpa.hibernate.ddl-auto=update

redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}
redis.password=${REDIS_PASSWORD}

server.port=3010